/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package greeter.app;

import greeter.GreetingFormatter;

public class Greeter {

    public static void main(String[] args) {
        final String output = GreetingFormatter.greeting(args[0]);
        System.out.println(output);
    }
}
